//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossSell_App.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Objective
    {
        
        public int Objective_Id { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<double> Score_Max { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> Score { get; set; }
        public string Level { get; set; }
        public int Metadata_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Questioner_Id { get; set; }
        public int Company_Id { get; set; }

        public virtual Company Company { get; set; }
        public virtual Questioner Questioner { get; set; }
        public virtual Metadata Metadata { get; set; }
        public virtual Objective Objectives1 { get; set; }
        public virtual Objective Objective1 { get; set; }





    }
}
